###########################
#    project specifics    #
###########################

language: minimal
dist: bionic

###########################
#      git specifics      #
###########################

# Only build travis and tags
if: branch = travis OR tag IS present

git:
    submodules: false
    depth: false

###########################
#       environment       #
###########################

env:
  global:
    - TRAVIS_MAVEN_FILE=djinni.jar
    - TRAVIS_MAVEN_SERVER_ID=appcom-maven-oss
    - TRAVIS_MAVEN_USER=appcom-ci
    # TRAVIS_MAVEN_PWD
    - secure: NkYbC3tXOOcBMPc8RyroiNLt+WajwbSll7RjLd6oCfXBy8O8Au03BtBP6jL7WCSSLxprRXCP+r0IcaAetmz4TO3bK9D7oE2Q467EvjlpOr4SoV1nhFOsDnMxhq4j08LiFY9dOw1QEQWiJAuFjTYuRCGUfRHD4PIB8vdW/6D6sfJa+EhsRoSI6jFhTTNYgEG8nnhwodX0sTzyvoEB4hYmcqH5Cj0hu7pI/AEZcw7bnZDN6THwAcf7aB2zLLr3xPe3XbqHHh8pNG59zSwo+wJGj/pPFIWXF1pe8qN6goQM0K5cq2/3hKJgAqE7Ocm+4mL3kUWf4TVkSRAYWwv+dBtknsitqMCtYsdsVQAXxx70AshPGkOzvH5HGPnmxC3cOngPkJJbB0mg3Q37ysRi8khFDXca7m9O7A5oWo5G+2eleXdAx4uMDgCE95OjP5L7bf9X3EHkilEcVhruCrQubTVevxiCY284uPT17AgNIR+NsJagSaL+8dppSDw6fSdKlOXXY3Ht2HQ2KZTSpOwh4ayN4OdBngntEEZUobiJZW9ypHfrgSyDw+OMsvfAnIZiUF81aw/nLLLF3yhswfqwp7hb8wmrCSr0512EOtBUaQl8c44iQOZq5X+o7vmBtSkmCgX/cYMJqzbTBgbm7AUF516RjNVXlZvMmioL1X8agN+4MCs=
    - TRAVIS_MAVEN_GROUP_ID="eu.appcom"
    - TRAVIS_MAVEN_ARTIFACT_ID=djinni
    - TRAVIS_MAVEN_URL="https://api.bintray.com/maven/appcom-interactive/appcom-maven-oss/djinni"
    - TRAVIS_MAVEN_VERSION=${TRAVIS_TAG}

###########################
#      job lifecycle      #
###########################

install:

  # install java, maven and sbt via sdkman.io
  - curl -s "https://get.sdkman.io" | bash
  - source "${HOME}/.sdkman/bin/sdkman-init.sh"
  - sdk install java
  - sdk install sbt
  - sdk install maven

script:

  # show OS and compiler version
  - uname -a

  # build the djinni fat file
  - make djinni_jar
  - cp src/target/scala-2.11/src-assembly-0.1-SNAPSHOT.jar djinni.jar

deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/provider/maven-upload.sh
  on:
    tags: true
